 
dataset:
  mot_dir: "/storage/user/seidensc/datasets/DanceTrack" # mot17_test_FRCNN
  det_dir: "/storage/user/seidensc/datasets/DanceTrack"
  det_file: "byte_out.txt" #"tracktor_prepr_det.txt" #"center_track.txt" #"qdtrack.txt" # "CenterTrack.txt" #"CenterTrackPub.txt" #"CSTrack.txt" #"FairMOT.txt" #"JDE.txt" #"TraDeS.txt" #"TransTrack.txt"  #"tmoh.txt" #
  detector: ""
  splits: "dance_val" #"mot17_split_1" #"mot17_split_2" #"mot17_split_3" #"mot17_train_test"
  validation_set: 0
  half_train_set_gt: 0 
  gt_assign_min_iou: 0.5
  sz_crop: [384, 128]
  fixed_aspect_ratio: 0

reid_net:
  mode: 'hyper_search'
  output: 'plain'
  trained_on:
    name: 'Market'
    num_classes: 2820 #751
  encoder_params:
    pretrained_path: 'ReID/trained_models/market_models/resnet50_Market.pth'
    net_type: "resnet50"
    add_distractors: 0
    neck: 0
    red: 4
    pool: 'max'

tracker:
  kalman: 0
  visualize: 0
  store_feats: 0
  use_bism: 0
  nan_first: 0
  assign_separately: 0
  random_patches_several_frames: 0
  several_frames: 0
  every_frame_several_frames: 0
  random_patches: 0
  random_patches_first: 0
  running_mean_seq: 0
  running_mean_seq_reset: 0
  first_batch: 0
  first_batch_reset: 0
  first_all: 0
  eval_bb: 0
  act_reid_thresh: 0.7
  inact_reid_thresh: 0.75
  det_conf: 0.6
  new_track_conf: 0.6
  inact_patience: 50
  output_dir: 'out' 
  avg_act:
    do: 0
    num: 0.95
    proxy: 'min_ioa'
  avg_inact: 
    do: 1
    num: 2
    proxy: 'each_sample'
  h_w_thresh: 1000000
  length_thresh: 0
  distance: 'cosine'
  motion_config:
    motion_compensation: 0
    num_iter_mc: 100
    warp_mode: 'Euclidean'
    termination_eps_mc: 0.00001
    apply_motion_model: 1
    center_only: 0
    combi: 'sum'
