mode: "gnn" #train/test/hyper_search/pretraining
application: "reid"

models:
  encoder_params:
    pretrained_path: "pretrained/0.8507772020726613neck_resnet50_cuhk03.pth" #"0.8469430051814687neck_resnet50_cuhk03.pth" #"0.8181347150260218neck_resnet50_cuhk03.pth" #"0.8352331606218806neck_resnet50_cuhk03.pth" #"no" #"0.79202072538871neck_resnet50_cuhk03.pth" # path to pretrained model
    net_type: "resnet50"
    neck: 1
    last_stride: 0
    weight_norm: 0
    final_drop: 0 #0.5
    stoch_depth: 1 #0.8
    bn_inception:
      embed: 0
      sz_embedding: 512

  gnn_params:
    pretrained_path: "no" 
    use_edge_encoder: 0
    use_edge_model: 0
    use_node_encoder: 0
    red: 4
    gnn:
      num_layers: 7
      aggregator: "add"
      num_heads: 4
      attention: "dot" #"dot_pygeo"
      mlp: 0
      dropout_mlp: 0.1
      norm1: 1
      norm2: 0
      res1: 1
      res2: 0
      dropout_1: 0.1
      dropout_2: 0
    edge:
      fc_dims: [2048]
      dropout_p: 0.4
      use_batchnorm: 0
    node_encoder:
      fc_dims: [2048]
      dropout_p: 0.4
      use_batchnorm: 0
    edge_encoder:
      fc_dims: [2048]
      dropout_p: 0.4
      use_batchnorm: 0
    classifier:
      neck: 1
      num_classes: 1367
      dropout_p: 0.4
      use_batchnorm: 0

graph_params:
  sim_type: "correlation"
  thresh: 0
  set_negative: "hard"

dataset:
  dataset_path: "../../datasets/cuhk03/detected"
  dataset_short: "cuhk03"
  num_classes: 1367
  trans: "bot" #"randaug" #"bot"
  number_aug: 2
  magnitude: 27
  sampling: "no"
  val: 0
  nb_workers: 4

train_params:
  num_classes_iter: 7 #12 #4 #4 #13 #5
  num_elements_class: 5 #10 #5 #4 #7 #2
  lr: 5.4573246693756151e-05 #1.3946574465280285e-05 #1.6176572774746115e-06 #1.677917830279509e-05 #6.675128594588672e-05 #4.4819286767613e-05
  weight_decay: 6.811554795084502e-09 #7.0881548682352635e-15 #1.0489199466864358e-09 #1.0191276954316531e-15 #4.1985936929920846e-12 #1.5288509425482333e-13
  num_epochs: 20
  is_apex: 0
  temperatur: 70
  output_train: "norm"
  loss_fn:
    fns: "gnn" #ce/focalce can be used instead of lsce and lsgnn/focalgnn instead of gnn, rest can be added by ce_gnn_center...
    scaling_ce: 1
    scaling_gnn: 1
    scaling_center: 0.5
    scaling_triplet: 1
    scaling_of: 5
    scaling_of_pre: 1
    scaling_distill: 1
    soft_temp: 1
eval_params:
  re_rank: 0
  lamb: 0.3
  k1: 20
  k2: 6
  output_test: "norm"







