mode: "pseudo" #train/test/hyper_search/pretraining
application: "DML"

models:
  encoder_params:
    pretrained_path: "pretrained/0.5183997299122215neck_resnet50_cub.pth" #"0.8532544378698225neck_resnet50_cub.pth" #"0.5183997299122215neck_resnet50_cub.pth" #"0.5146860229574611neck_resnet50_cub.pth" #"0.5183997299122215neck_resnet50_cub.pth" 
    net_type: "resnet50"
    neck: 1
    last_stride: 0
    final_drop: 0 #0.5
    stoch_depth: 1 #0.8
    weight_norm: 0
    bn_inception:
      embed: 0
      sz_embedding: 512

  gnn_params:
    pretrained_path: "no" #"0.9857227840571089gnn_neck_resnet50_Market.pth"
    use_edge_encoder: 0
    use_edge_model: 0
    use_node_encoder: 0
    red: 1
    gnn:
      num_layers: 7
      aggregator: "add"
      num_heads: 4
      attention: "dot" #"dot_pygeo"
      mlp: 0
      dropout_mlp: 0.1
      norm1: 1
      norm2: 0
      res1: 1
      res2: 0
      dropout_1: 0.1
      dropout_2: 0
    edge:
      fc_dims: [2048]
      dropout_p: 0.4
      use_batchnorm: 0
    node_encoder:
      fc_dims: [2048]
      dropout_p: 0.4
      use_batchnorm: 0
    edge_encoder:
      fc_dims: [2048]
      dropout_p: 0.4
      use_batchnorm: 0
    classifier:
      neck: 1
      num_classes: 100
      dropout_p: 0.4
      use_batchnorm: 0

graph_params:
  sim_type: "correlation"
  thresh: 0
  set_negative: "hard"

dataset:
  dataset_path: "../../datasets/CUB_200_2011"
  dataset_short: "cub"
  num_classes: 100
  number_aug: 2
  magnitude: 27
  trans: "bot"
  sampling: "no"
  val: 0
  nb_workers: 4

train_params:
  num_classes_iter: 4 #6 #4 #5 #6
  num_elements_class: 10 #9 #10 #4 #9
  lr: 4.556233790187342e-06 #0.0001563663718906821 #4.556233790187342e-06 #1.5555986096652693e-05 #0.0001563663718906821
  weight_decay: 2.4790123787229617e-08 #6.059722614369727e-06 #2.4790123787229617e-08 #3.558002740229624e-07 #6.059722614369727e-06
  num_epochs: 20
  is_apex: 0
  temperatur: 24
  output_train: "norm"
  loss_fn:
    fns: "gnn" #ce/focalce can be used instead of lsce and lsgnn/focalgnn instead of gnn, rest can be added by ce_gnn_center...
    scaling_ce: 1
    scaling_gnn: 1
    scaling_center: 0.5
    scaling_triplet: 1
    scaling_of: 5
    scaling_of_pre: 1
    scaling_distill: 1
    soft_temp: 1
    feats: "results/0.8532544378698225_cub_1601148947.5862918/feats.json"
    preds: "results/0.8532544378698225_cub_1601148947.5862918/preds.json"

eval_params:
  re_rank: 0
  lamb: 0.3
  k1: 20
  k2: 6
  output_test: "norm"







