dataset:
  mot_dir: "/storage/slurm/seidensc/datasets/MOT/MOT17" # mot17_test_FRCNN
  det_dir: "/storage/slurm/seidensc/datasets/MOT/MOT17Labels"
  det_file: "tracktor_prepr_det.txt"
  detector: "all" #"all" #"FRCNN"
  splits: "mot17_train_test" #"mot17_split_1_test" #
  gt_assign_min_iou: 0.5
  prepro_again: 0
  gt_training_min_vis: 0
  drop_unassigned: 0
  save_oracle: 0

reid_net:
  mode: 'hyper_search'
  gnn: 0
  save_folder_nets: 'nets'
  trained_on:
    name: 'Market'
    num_classes: 2820 #751
  dl_params:
    num_classes_iter: 7
    num_elements_class: 3
    batch_sampler: "no"
  train_params:
    temperature: 80
    epochs: 70
    lr: 0.2 
    weight_decay: 0.2
  encoder_params:
    pretrained_path: "ReID/models/0.8598574821852731resnet50FPN_Market.pth" #"ReID/models/0.8687648456057007resnet50FPN_Market.pth" #"ReID/models/0.8678741092636579resnet50FPN_Market.pth" # Deterministic models norm small "ReID/0.8678741092636579resnet50FPN_Market.pth" #"ReID/0.8331353919239906resnet50FPN_Market.pth" "ReID/0.871437054631829resnet50FPN_Market.pth" "ReID/0.8634204275534442resnet50_Market.pth" # Deterministic models bot small "ReID/0.8821258907363421resnet50_Market.pth" "ReID/0.8874703087885986resnet50FPN_Market.pth" "ReID/0.880938242280285resnet50FPN_Market.pth" "ReID/0.8815320665083135resnet50FPN_Market.pth" # Deterministic models large "ReID/0.8966745843230404resnet50FPN_Market.pth" "ReID/0.8672802850356295resnet50_Market.pth" "ReID/0.8824228028503563resnet50FPN_Market.pth" "ReID/0.8913301662707839resnet50FPN_Market.pth" #"ReID/0.8963776722090261resnet50FPN_Market.pth" "ReID/0.8847980997624703resnet50FPN_Market.pth" "ReID/0.8919239904988123resnet50FPN_Market.pth" "ReID/0.8770783847980997resnet50_Market.pth" #"weights/0.9233103714051737resnet50_Market.pth" #"../again_gnn_reid/gnn_based_reid/storage/search_results_net/all_experiemnts/0.9050050580471121resnet50FPN_Market.pth" #"../gnn_based_reid/storage/search_results_net/market_experiments/0.9364608076009501resnet50FPN_Market.pth" #'../gnn_based_reid/storage/search_results_net/prw.pth' #"../gnn_based_reid/storage/search_results_net/all_experiemnts/0.9328002312250109resnet50_Market.pth" #"../gnn_based_reid/storage/search_results_net/all_experiemnts/0.9474926537887182resnet50_Market.pth" #"../gnn_based_reid/storage/search_results_net/all_experiemnts/0.9290909966761405resnet50_Market.pth" #"../gnn_based_reid/storage/search_results_net/all_experiemnts/0.9339563562792041resnet50_Market.pth" #"../gnn_based_reid/storage/search_results_net/0.9339563562792041resnet50_Market.pth" #"../again_gnn_reid/gnn_based_reid/storage/search_results_net/market_experiments/0.9768408551068883resnet50_Market.pth" #"../again_gnn_reid/gnn_based_reid/storage/search_results_net/market_experiments/0.9593230403800475resnet50FPN_Market.pth" #"../again_gnn_reid/gnn_based_reid/storage/search_results_net/0.9219121140142518resnet50_Market.pth" #"../again_gnn_reid/gnn_based_reid/storage/search_results_net/market_experiments/0.9364608076009501resnet50FPN_Market.pth" 
    net_type: "resnet50_analysis" #"batch_drop_block" #"bot" #"resnet50" #"resnet50_analysis" 
    neck: 0
    red: 1 #4
    last_stride: 0
    final_drop: 0 #0.5
    stoch_depth: 1 #0.8
    weight_norm: 0
    bn_inception:
      embed: 0
      sz_embedding: 512
  graph_params:
    sim_type: "correlation"
    thresh: 0
    set_negative: "hard"
  gnn_params:
    pretrained_path: "../gnn_based_reid/storage/search_results_net/0.14578384798099764gnn_resnet50_attention_Market.pth" #"../gnn_based_reid/storage/search_results_net/market_experiments/0.9364608076009501gnn_resnet50FPN_Market.pth" #'../gnn_based_reid/storage/search_results_net/gnn_prw.pth' #"weights/0.9233103714051737gnn_resnet50_Market.pth" #"../gnn_based_reid/storage/search_results_net/all_experiemnts/0.9474926537887182gnn_resnet50_Market.pth" #"../gnn_based_reid/storage/search_results_net/0.9339563562792041gnn_resnet50_Market.pth" #"weights/0.9233103714051737gnn_resnet50_Market.pth" #"../again_gnn_reid/gnn_based_reid/storage/search_results_net/market_experiments/0.9768408551068883resnet50_Market.pth" #"../again_gnn_reid/gnn_based_reid/storage/search_results_net/market_experiments/0.9593230403800475gnn_resnet50FPN_Market.pth" #"../again_gnn_reid/gnn_based_reid/storage/search_results_net/0.9219121140142518gnn_resnet50_Market.pth" #"../again_gnn_reid/gnn_based_reid/storage/search_results_net/market_experiments/0.9364608076009501gnn_resnet50FPN_Market.pth"
    use_edge_encoder: 0
    use_edge_model: 0
    use_node_encoder: 0
    red: 1
    cat: 0
    every: 0
    proxies: 0
    gnn:
      num_layers: 2 #1 
      aggregator: "add"
      num_heads: 8 #
      attention: "dot" #"dot_pygeo"
      mlp: 1
      dropout_mlp: 0.1
      norm1: 1
      norm2: 1
      res1: 1
      res2: 1
      dropout_1: 0.1
      dropout_2: 0.1
      mult_attr: 0
    edge:
      fc_dims: [2048]
      dropout_p: 0.4
      use_batchnorm: 0
    node_encoder:
      fc_dims: [2048]
      dropout_p: 0.4
      use_batchnorm: 0
    edge_encoder:
      fc_dims: [2048]
      dropout_p: 0.4
      use_batchnorm: 0
    classifier:
      neck: 1
      num_classes: 2820 #751
      dropout_p: 0.4
      use_batchnorm: 0


tracker:
  random_patches: 0
  running_mean_seq: 0
  running_mean_seq_reset: 0
  first_batch: 0
  first_batch_reset: 0
  eval_bb: 1
  use_sr_gan: 0
  gallery_att: 0
  norm_dist: 0
  get_reid_performance: 0
  oracle: 0
  oracle_iou: 0
  iou_thresh: 0
  occluder_thresh: 0
  jaccard_thresh: 0
  oracle_size: 0
  size_thresh: 0
  oracle_frame_dist: 0
  frame_dist_thresh: 0
  oracle_size_diff: 0
  size_diff_thresh: 0
  gallery_vis_thresh: 0
  rel_gallery_vis_thresh: 0 
  only_next_frame: 0
  oracle_position: 0
  position_thresh: 0
  oracle_disappear: 0
  oracle_appear: 0
  interpolate: 0
  act_reid_thresh: 0.35 #0.55 #0.2 #0.05 #0.45 #0.45 #0.35 #0.65 #0.55 #0.65 #0.7 #0.45
  inact_reid_thresh: 0.25 #0.25 #0.125 #0.901 #0.04 #0.35 #0.35 #0.35 #0.5 #0.5 #0.5 #0.5 #0.35
  inact_thresh: 100000
  output_dir: 'out'
  avg_act:
    do: 0
    num: 4 #'uniform_3' #60 #10 #4 #20 #'all'
    proxy: 'mode' #'frames_gnn' #'frames_gnn' #'mode'
  avg_inact: 
    do: 1
    num: 80 #'uniform_3' #'mean' #'uniform_4' #10 #4 #20 #'all'
    proxy: 'mode' #'60' #'frames_gnn' #'frames_gnn' #'mode'
  init_tracktor: 
    do: 0
  h_w_thresh: 10000
  length_thresh: 2
