dataset:
  mot_dir: "../../datasets/MOT/MOT17" # mot17_test_FRCNN
  det_dir: "../../datasets/MOT/MOT17Labels"
  det_file: "tracktor_prepr_det.txt"
  detector: "FRCNN"
  splits: "debug_train" #"mot17_train_test" #"mot17_split_1"
  gt_assign_min_iou: 0.5
  prepro_again: 0
  gt_training_min_vis: 0

reid_net:
  mode: 'hyper_search'
  gnn: 1
  save_folder_nets: 'nets'
  trained_on:
    name: 'Market'
    num_classes: 751
  dl_params:
    num_classes_iter: 7
    num_elements_class: 3
    batch_sampler: "no"
  train_params:
    temperature: 80
    epochs: 70
    lr: 0.2
    weight_decay: 0.2
  encoder_params:
    pretrained_path: "../again_gnn_reid/gnn_based_reid/storage/search_results_net/0.9049881235154394resnet50_Market.pth" #"weights/reid_market.pth" #"../again_gnn_reid/gnn_based_reid/storage/search_results_net/0.9046912114014252resnet50_Market.pth" #"../again_gnn_reid/gnn_based_reid/storage/search_results_net/0.8666864608076009resnet50_Market.pth"
    net_type: "resnet50"
    neck: 0
    red: 4
    last_stride: 0
    final_drop: 0 #0.5
    stoch_depth: 1 #0.8
    weight_norm: 0
    bn_inception:
      embed: 0
      sz_embedding: 512
  graph_params:
    sim_type: "correlation"
    thresh: 0
    set_negative: "hard"
  gnn_params:
    pretrained_path: "../again_gnn_reid/gnn_based_reid/storage/search_results_net/0.9049881235154394gnn_resnet50_Market.pth" #"weights/reid_gnn_market.pth" #"../again_gnn_reid/gnn_based_reid/storage/search_results_net/0.9046912114014252gnn_resnet50_Market.pth" #"../again_gnn_reid/gnn_based_reid/storage/search_results_net/0.8666864608076009gnn_resnet50_Market.pth"  
    use_edge_encoder: 0
    use_edge_model: 0
    use_node_encoder: 0
    red: 1
    cat: 0
    every: 0
    proxies: 0
    gnn:
      num_layers: 1 #2 #1 
      aggregator: "add"
      num_heads: 8 #8 #8
      attention: "dot" #"dot_pygeo"
      mlp: 1
      dropout_mlp: 0.1
      norm1: 1
      norm2: 1
      res1: 1
      res2: 1
      dropout_1: 0.1
      dropout_2: 0.1
      mult_attr: 0
    edge:
      fc_dims: [2048]
      dropout_p: 0.4
      use_batchnorm: 0
    node_encoder:
      fc_dims: [2048]
      dropout_p: 0.4
      use_batchnorm: 0
    edge_encoder:
      fc_dims: [2048]
      dropout_p: 0.4
      use_batchnorm: 0
    classifier:
      neck: 1
      num_classes: 751
      dropout_p: 0.4
      use_batchnorm: 0


tracker:
  reid_thresh: 1
  inact_thresh: 20
  output_dir: 'out'
  avg_inact: 
    do: 1
    num: 'all'
    proxy: 'mean'
  init_tracktor: 
    do: 0
