mode: "hyper_search" #train/test/hyper_search/pretraining
application: "DML"

models:
  encoder_params:
    pretrained_path: "no" #"pretrained/0.33782354302337114neck_resnet50_sop.pth"
    net_type: "resnet50"
    neck: 0
    last_stride: 0
    final_drop: 0 #0.5
    stoch_depth: 1 #0.8
    weight_norm: 0
    red: 4
    bn_inception:
      embed: 0
      sz_embedding: 512

  gnn_params:
    pretrained_path: "no" 
    use_edge_encoder: 0
    use_edge_model: 0
    use_node_encoder: 0
    red: 1
    cat: 0
    every: 0
    proxies: 0
    gnn:
      num_layers: 1 #2
      aggregator: "add"
      num_heads: 4 #4
      attention: "dot" #"dot_pygeo"
      mlp: 1
      dropout_mlp: 0.1
      norm1: 1
      norm2: 1
      res1: 1
      res2: 1
      dropout_1: 0.1
      dropout_2: 0.1
      mult_attr: 0
    edge:
      fc_dims: [2048]
      dropout_p: 0.4
      use_batchnorm: 0
    node_encoder:
      fc_dims: [2048]
      dropout_p: 0.4
      use_batchnorm: 0
    edge_encoder:
      fc_dims: [2048]
      dropout_p: 0.4
      use_batchnorm: 0
    classifier:
      neck: 1
      num_classes: 11318
      dropout_p: 0.4
      use_batchnorm: 0

graph_params:
  sim_type: "correlation"
  thresh: 0
  set_negative: "hard"

dataset:
  dataset_path: "../../datasets/Stanford_Online_Products"
  dataset_short: "sop"
  num_classes: 11318
  trans: "GL_orig_RE"
  number_aug: 2
  magnitude: 27
  sampling: "no"
  bssampling: "NumberSampler"
  val: 0
  nb_workers: 4

train_params:
  num_classes_iter: 8 #10 #70 #10
  num_elements_class: 4 #6 #5 #6
  lr: 0.00014695698961273638 #0.0006077651100709081 #6.672588679081452e-05 #0.0006077651100709081 
  weight_decay: 3.008975204210844e-15 #5.2724883734490575e-12 #4.034721886446752e-15 #5.2724883734490575e-12
  num_epochs: 70
  is_apex: 0
  temperatur: 0.8222229277845058 #0.2 #0.6968750970069256 #0.2
  output_train_enc: "plain"
  output_train_gnn: "plain"
  loss_fn:
    fns: "lsce_lsgnn" #ce/focalce can be used instead of lsce and lsgnn/focalgnn instead of gnn, rest can be added by ce_gnn_center...
    scaling_ce: 1
    scaling_gnn: 1
    scaling_center: 0.5
    scaling_triplet: 1
    scaling_of: 1
    scaling_of_pre: 1
    scaling_distill: 1
    soft_temp: 10
    preds: 
    feats: 

eval_params:
  re_rank: 0
  lamb: 0.3
  k1: 20
  k2: 6
  output_test_enc: "plain"
  output_test_gnn: "plain"
  cat: 0
