mode: "train" 
application: "reid"
visualize: 0

encoder:
  pretrained_path: "no" 
  net_type: "resnet50"
  neck: 0
  add_distractors: 0
  red: 4
  pool: 'max'

dataset:
  dataset_path: "datasets/Market-1501-v15.09.15"
  dataset_short: "Market"
  num_classes: 751
  split: "no"
  trans: "norm"
  bssampling: "no" 
  rand_scales: 0
  nb_workers: 4
  add_distractors: 0
  sz_crop: [384, 128]

train_params:
  store_every: 0
  milestones: [31, 51]
  lr_reduction: [0.1, 0.1]
  num_classes_iter: 7 
  num_elements_class: 3 
  lr: 0.00011067818445868948 
  weight_decay: 2.376601518887915e-15 
  num_epochs: 70
  is_apex: 0
  temperatur: 0.1111111111111 
  output_train_enc: "plain"
  loss_fn:
    fns: "lsce"
    scaling_ce: 1
    scaling_bce: 1
    scaling_triplet: 1

eval_params:
  output_test_enc: "plain"
